# Fix the code
print("Aapo")
print("Eero")
print("Juhani")
print("Lauri")
print("Simeoni")
print("Timo")
print("Tuomas")
# print("Welcome to Introduction to Programming!")
# print("First we will practice using the print command.")
# print("This program prints three lines of text on the screen.")
